pub mod config;
#[cfg(not(target_arch = "wasm32"))]
pub mod conversion;
pub mod error;
pub mod extract;
pub mod ocr;
pub mod ocr_merge;
pub mod output;
pub mod parser;
pub mod projection;
#[cfg(not(target_arch = "wasm32"))]
pub mod render;
pub mod search;
pub mod types;
