/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsLiteParseConfig {
  /** OCR language code (e.g., "eng", "fra"). */
  ocrLanguage?: string
  /** Whether OCR is enabled. */
  ocrEnabled?: boolean
  /** HTTP OCR server URL. If set, uses HTTP OCR instead of Tesseract. */
  ocrServerUrl?: string
  /** Path to tessdata directory for Tesseract. */
  tessdataPath?: string
  /** Maximum number of pages to parse. */
  maxPages?: number
  /** Specific pages to parse (e.g., "1-5,10,15-20"). */
  targetPages?: string
  /** DPI for rendering pages (used for OCR and screenshots). */
  dpi?: number
  /** Output format: "json", "text", or "markdown". */
  outputFormat?: string
  /** Keep very small text that would normally be filtered out. */
  preserveVerySmallText?: boolean
  /** Password for encrypted/protected documents. */
  password?: string
  /** Suppress progress output. */
  quiet?: boolean
  /** Number of concurrent OCR workers (default: CPU cores - 1). */
  numWorkers?: number
}
export interface JsTextItem {
  text: string
  x: number
  y: number
  width: number
  height: number
  fontName?: string
  fontSize?: number
  confidence?: number
}
export interface JsParsedPage {
  pageNum: number
  width: number
  height: number
  text: string
  textItems: Array<JsTextItem>
}
export interface JsParseResult {
  pages: Array<JsParsedPage>
  text: string
}
export interface JsScreenshotResult {
  pageNum: number
  width: number
  height: number
  imageBuffer: Buffer
}
/** Search text items for phrase matches, returning merged items with combined bounding boxes. */
export declare function searchItems(items: Array<JsTextItem>, phrase: string, caseSensitive?: boolean | undefined | null): Array<JsTextItem>
/** Main LiteParse parser class. */
export declare class LiteParse {
  /**
   * Create a new LiteParse instance with optional configuration.
   * Any fields not provided will use defaults.
   */
  constructor(config?: JsLiteParseConfig | undefined | null)
  /** Parse a document. Accepts a file path (string) or raw PDF bytes (Buffer). */
  parse(input: string | Buffer): Promise<JsParseResult>
  /**
   * Take screenshots of document pages. Returns PNG image buffers.
   *
   * Non-PDF files are automatically converted to PDF before rendering when
   * LibreOffice/ImageMagick are available.
   */
  screenshot(input: string | Buffer, pageNumbers?: Array<number> | undefined | null): Promise<Array<JsScreenshotResult>>
  /** Get the current configuration. */
  get config(): JsLiteParseConfig
}
